In [10]:
import math
import numpy as np
import pandas as pd

In [11]:
class BiscectionMethod:
    
    def __init__(self, ponto_a : float, ponto_b : float, precisao : float, funcao ) :
        self.ponto_a = ponto_a
        self.ponto_b = ponto_b
        self.precisao = precisao
        self.funcao = funcao
        self.__tabela = None
        self.__relacao = list()
    
    def get_raiz(self) :
        raiz_encontrada = False

        while(not raiz_encontrada) :
            x = np.array([self.ponto_a, self.ponto_b]).mean()
            erro_relativo = (abs(x - self.ponto_a)/np.array([1, x]).max())
            
            linha = (self.ponto_a, self.ponto_b, self.funcao(self.ponto_a), self.funcao(self.ponto_b), x, self.funcao(x), erro_relativo)
            self.__relacao.append(linha)
            
            if( erro_relativo < self.precisao) :
                raiz = x
                raiz_encontrada = True
            else:
                if self.funcao(self.ponto_a) * self.funcao(x) < 0:
                    self.ponto_b = x
                else:
                    self.ponto_a = x
        return raiz
    
    @property
    def tabela(self):
        self.__tabela = pd.DataFrame(self.__relacao, columns=["a", "b", "f(a)", "f(b)","X_k", "f(X_k)", "Erro relativo"])
        return self.__tabela

In [12]:
### 4.(a)
def funcao_a(x : float):
    return pow(x,2) - math.sin(x)

### 4.(b)
def funcao_b(x : float):
    return math.cos(math.pi*(x+1)/8) + 0.148 * x -0.9062

### 4.(c)
def funcao_c(x : float):
    return pow(x, 2) + math.log(x)

### 4.(d)
def funcao_d(x : float):
    return x * math.pow(math.e, x) - 1

### 4.(a)

In [13]:
problemaA = BiscectionMethod(0.5, 1, 0.01, funcao_a)
print("Raiz a partir do objeto eh: {}".format(problemaA.get_raiz()))
problemaA.tabela

Raiz a partir do objeto eh: 0.8828125

       a         b      f(a)      f(b)       X_k    f(X_k)  Erro relativo
0  0.500  1.000000 -0.229426  0.158529  0.750000 -0.119139       0.250000
1  0.750  1.000000 -0.119139  0.158529  0.875000 -0.001919       0.125000
2  0.875  1.000000 -0.001919  0.158529  0.937500  0.072825       0.062500
3  0.875  0.937500 -0.001919  0.072825  0.906250  0.034092       0.031250
4  0.875  0.906250 -0.001919  0.034092  0.890625  0.015748       0.015625
5  0.875  0.890625 -0.001919  0.015748  0.882812  0.006830       0.007812

### 4.(b).I

In [14]:
problemaB = BiscectionMethod(-1, 0, 0.01, funcao_b)
print("Raiz a partir do objeto eh: {}".format(problemaB.get_raiz()))
problemaB.tabela

Raiz a partir do objeto eh: -0.5078125

          a    b      f(a)      f(b)       X_k    f(X_k)  Erro relativo
0 -1.000000  0.0 -0.054200  0.017680 -0.500000  0.000585       0.500000
1 -1.000000 -0.5 -0.054200  0.000585 -0.750000 -0.022015       0.250000
2 -0.750000 -0.5 -0.022015  0.000585 -0.625000 -0.009523       0.125000
3 -0.625000 -0.5 -0.009523  0.000585 -0.562500 -0.004172       0.062500
4 -0.562500 -0.5 -0.004172  0.000585 -0.531250 -0.001720       0.031250
5 -0.531250 -0.5 -0.001720  0.000585 -0.515625 -0.000549       0.015625
6 -0.515625 -0.5 -0.000549  0.000585 -0.507812  0.000023       0.007812

### 4.(b).II

In [15]:
problemaB2 = BiscectionMethod(0, 1, 0.01, funcao_b)
print("Raiz a partir do objeto eh: {}".format(problemaB2.get_raiz()))
problemaB.tabela

Raiz a partir do objeto eh: 0.4921875

          a    b      f(a)      f(b)       X_k    f(X_k)  Erro relativo
0 -1.000000  0.0 -0.054200  0.017680 -0.500000  0.000585       0.500000
1 -1.000000 -0.5 -0.054200  0.000585 -0.750000 -0.022015       0.250000
2 -0.750000 -0.5 -0.022015  0.000585 -0.625000 -0.009523       0.125000
3 -0.625000 -0.5 -0.009523  0.000585 -0.562500 -0.004172       0.062500
4 -0.562500 -0.5 -0.004172  0.000585 -0.531250 -0.001720       0.031250
5 -0.531250 -0.5 -0.001720  0.000585 -0.515625 -0.000549       0.015625
6 -0.515625 -0.5 -0.000549  0.000585 -0.507812  0.000023       0.007812

### 4.(c)

In [16]:
problemaC = BiscectionMethod(0.5, 1, 0.01, funcao_c)
print("Raiz a partir do objeto eh: {}".format(problemaC.get_raiz()))
problemaC.tabela

Raiz a partir do objeto eh: 0.6484375

          a        b      f(a)      f(b)       X_k    f(X_k)  Erro relativo
0  0.500000  1.00000 -0.443147  1.000000  0.750000  0.274818       0.250000
1  0.500000  0.75000 -0.443147  0.274818  0.625000 -0.079379       0.125000
2  0.625000  0.75000 -0.079379  0.274818  0.687500  0.097963       0.062500
3  0.625000  0.68750 -0.079379  0.097963  0.656250  0.009451       0.031250
4  0.625000  0.65625 -0.079379  0.009451  0.640625 -0.034911       0.015625
5  0.640625  0.65625 -0.034911  0.009451  0.648438 -0.012718       0.007812

### 4.(d)

In [17]:
problemaC = BiscectionMethod(0.5, 1, 0.01, funcao_c)
print("Raiz a partir do objeto eh: {}".format(problemaC.get_raiz()))
problemaC.tabela

Raiz a partir do objeto eh: 0.5703125

        a         b      f(a)      f(b)       X_k    f(X_k)  Erro relativo
0  0.5000  1.000000 -0.175639  1.718282  0.750000  0.587750       0.250000
1  0.5000  0.750000 -0.175639  0.587750  0.625000  0.167654       0.125000
2  0.5000  0.625000 -0.175639  0.167654  0.562500 -0.012782       0.062500
3  0.5625  0.625000 -0.012782  0.167654  0.593750  0.075142       0.031250
4  0.5625  0.593750 -0.012782  0.075142  0.578125  0.030619       0.015625
5  0.5625  0.578125 -0.012782  0.030619  0.570312  0.008780       0.007812

In [19]:
problemaA.tabela.to_csv("Resultado questao 4(a).csv", ";", index=False)
problemaB.tabela.to_csv("Resultado questao 4(b)i.csv", ";", index=False)
problemaB2.tabela.to_csv("Resultado questao 4(b)ii.csv", ";", index=False)
problemaC.tabela.to_csv("Resultado questao 4(c).csv", ";", index=False)
problemaD.tabela.to_csv("Resultado questao 4(d).csv", ";", index=False)